# To change any variable, you always need to use the prefix (the prefix is set inside the file "app/config.go")
# and also all letters should be upper case.
#   Example:
#     - To change the dsn var, you need to export an env var "API_DSN", because by default the prefix is APP

# Debug mode
debug: true

# Relational database config
db:
  dbname: bank
  dialect: mongodb
  endpoint: "http://172.17.0.2:27019"
  max_idle_connections: 10
  max_open_connections: 10

# Session JWT token
session_token:
  audience: "https://api.proteinportal.com.br"
  # Duration in days
  duration: 60
  issuer: "https://api.proteinportal.com.br"
  secret: secret

# Cache config
cache:
  defaultExpire: 5 #minutes
  defaultPurge: 10 #minutes

#S3
file_storage:
  endpoint: "localhost:9000"
  access_key_id: key123
  secret_access_key: secret123
  ssl: false
  temp_bucket: temp-files
  products_bucket: products
  suppliers_bucket: suppliers
  base_url: "http://localhost:9000"

# Api host and port
# host: "0.0.0.0"
host: localhost
port: 8081
cors:
  allow_origins:
    - '*'
  allow_headers:
    - Content-Type
    - Accept
    - Referer
    - Authorization
    - Cache-Control
    - X-Requested-With
  expose_headers:
    - Api-Token
  allow_credentials: false

log:
  level: debug
  outputs:
    stdout: true
    file:
      enabled: true
      path: '/tmp/protein-portal.log'
